# Generated by Django 4.2.2 on 2023-06-21 16:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(error_messages={'unique': 'This ID is already in use !'}, max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('runtime', models.IntegerField()),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('year', models.IntegerField()),
                ('director', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
                ('production', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('cover', models.CharField(max_length=250)),
                ('plot', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Name should only contain letters', regex='^[a-zA-z]+$')])),
                ('lname', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Name should only contain letters', regex='^[a-zA-z]+$')])),
                ('email', models.EmailField(error_messages={'unique': 'This Email is already in use !'}, max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'This Username is already in use !'}, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Username can contain only letters, numbers and underscores', regex='^[a-zA-z0-9_]+$')])),
                ('password', models.CharField(max_length=250)),
                ('DOB', models.CharField(max_length=15)),
                ('likes', models.JSONField(blank=True, null=True)),
                ('watched', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
