# Generated by Django 4.2.2 on 2023-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
