# Generated by Django 4.2.2 on 2023-06-24 18:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_user_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
